name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-beijing:
    name: Deploy to BEIJING
    runs-on: self-hosted
    environment:
      name: 北京蓟门服务器集群

    steps:
      - name: Deploy to BEIJING servers
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          ssh -6 \
            -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST_BEIJING }} \
            "
            cd /home/deploy/leak-check.garinasset.com &&
            git fetch origin &&
            git reset --hard ${COMMIT_SHA} &&
            chmod +x deploy.sh &&
            ./deploy.sh
            "

  deploy-shandong:
    name: Deploy to SHANDONG
    runs-on: self-hosted
    environment:
      name: 山东齐鲁服务器集群

    steps:
      - name: Deploy to SHANDONG servers
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          ssh -6 \
            -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST_SHANDONG }} \
            "
            cd /home/deploy/leak-check.garinasset.com &&
            git fetch origin &&
            git reset --hard ${COMMIT_SHA} &&
            chmod +x deploy.sh &&
            ./deploy.sh
            "